import { Imobile } from "../model/mobile";

export const mobileProducts: Array<Imobile> = [
    {
      id: 1,
      name: 'iPhone 13',
      brand: 'Apple',
      price: 999,
      originalPrice:1200,
      image: 'https://i.insider.com/6116b065c040ad0018ce3ea1?width=1009&format=jpeg',
      isAvailable: true,
      rating : 4.9,
      noOfItem: 50,
      specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    },
    {
      id: 2,
      name: 'Samsung Galaxy S21',
      brand: 'Samsung',
      price: 899,
      originalPrice:1000,
      image: '',
      isAvailable: false,
      rating : 4.5,
      noOfItem: 8,specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    },
    {
      id: 3,
      name: 'Google Pixel 6',
      brand: 'Google',
      price: 799,
      originalPrice:900,
      image: 'https://support.apple.com/library/content/dam/edam/applecare/images/en_US/iOS/ios16-iphone13-pro-widgets-home-screen.png',
      isAvailable: false,
      rating : 3.9,
      noOfItem: 6,
      specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    },
    {
      id: 4,
      name: 'OnePlus 9 Pro',
      brand: 'OnePlus',
      price: 899,
      originalPrice:950,
      image: '',
      isAvailable: true,
      rating : 2.9,
      noOfItem: 70,
      specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    },
    {
      id: 5,
      name: 'Xiaomi Mi 11',
      brand: 'Xiaomi',
      price: 699,
      originalPrice:800,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
      isAvailable: true,
      rating : 4.8,
      noOfItem: 80,
      specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    },
    {
      id: 6,
      name: 'Sony Xperia 1 III',
      brand: 'Sony',
      price: 1199,
      originalPrice:1500,
      image: '',
      isAvailable: true,
      rating : 2.5,
      noOfItem: 30,
      specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    },
    {
      id: 7,
      name: 'LG Velvet',
      brand: 'LG',
      price: 599,
      originalPrice:700,
      image: '',
      isAvailable: false,
      rating : 1.5,
      noOfItem: 400,
      specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    },
    {
      id: 8,
      name: 'Huawei P40 Pro',
      brand: 'Huawei',
      price: 899,
      originalPrice:1000,
      image: '',
      isAvailable: true,
      rating : 3.5,
      noOfItem: 5,
      specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    },
    {
      id: 9,
      name: 'Motorola Moto G Power',
      brand: 'Motorola',
      price: 249,
      originalPrice:300,
      image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR_RzdvwZ2YQZDdcxwdHPXPk9hRMqtaX3ZbSA&usqp=CAU',
      isAvailable: true,
      rating : 4.5,
      noOfItem: 90,
      specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    },
    {
      id: 10,
      name: 'Nokia 8.3',
      brand: 'Nokia',
      price: 499,
      originalPrice:700,
      image: '',
      isAvailable: true,
      rating : 4.5,
      noOfItem: 35,
      specification:["8 GB RAM ", "256 GB ROM",
        "16.26 cm (6.4 inch) Full HD+ Display",
        "50MP + 12MP | 10MP Front Camera",
       " 4500 mAh Battery",
       " Samsung Exynos 2200 Processo"]
    }
  
  ];